[[override]]
  name = "github.com/tektoncd/triggers"
  version = "v0.4.0"

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.12"

[[override]]
  name = "k8s.io/api"
  version = "v0.16.5"

[[override]]
  name = "k8s.io/apimachinery"
  version = "v0.16.5"

[[override]]
  name = "k8s.io/client-go"
  version = "v0.16.5"

[[override]]
  name = "github.com/openshift/client-go"
  branch = "release-4.3"

[[override]]
  name = "github.com/openshift/api"
  branch = "release-4.3"

[[override]]
  name = "github.com/tektoncd/pipeline"
  version = "v0.11.0"

[prune]
  go-tests = true
  unused-packages = true